import Link from 'next/link';
import styles from '../legal.module.css';

export const metadata = {
  title: 'Terms of Service — AskAway',
};

export default function TermsPage() {
  return (
    <div className={styles.page}>
      <Link href="/" className={styles.back}>← Back to AskAway</Link>

      <h1 className={styles.title}>Terms of Service</h1>
      <p className={styles.meta}>Effective Date: March 31, 2026</p>

      <p className={styles.intro}>
        Please read these Terms of Service ("Terms") carefully before using AskAway at askaway.guide (the "Service").
        By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
      </p>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>1. Acceptance of Terms</h2>
        <div className={styles.body}>
          <p>These Terms constitute a legally binding agreement between you and Future Products LLC, the operator of AskAway. You represent that you are at least 13 years of age and have the legal capacity to enter into this agreement. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>2. Description of Service</h2>
        <div className={styles.body}>
          <p>AskAway is a free AI-powered tool designed to help people get value from artificial intelligence in an accessible way. The Service is provided "as is" and may change or be discontinued at any time without notice.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>3. Permitted Use</h2>
        <div className={styles.body}>
          <p>You agree to use AskAway only for lawful purposes and in a manner consistent with these Terms. You may use the Service to:</p>
          <ul>
            <li>Ask questions and receive AI-generated responses</li>
            <li>Explore and learn about topics of personal interest</li>
            <li>Generate written content for your own use</li>
          </ul>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>4. Prohibited Conduct</h2>
        <div className={styles.body}>
          <p>You agree NOT to use AskAway to:</p>
          <ul>
            <li>Submit content that is unlawful, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable</li>
            <li>Generate, distribute, or promote content that exploits or harms minors in any way</li>
            <li>Attempt to deceive, impersonate, or defraud any person or entity</li>
            <li>Engage in any activity that violates applicable local, state, national, or international law or regulation</li>
            <li>Probe, scan, or test the vulnerability of the Service or any related system or network</li>
            <li>Introduce malware, viruses, or any code designed to interrupt, destroy, or limit the functionality of the Service</li>
            <li>Use automated means (bots, scrapers, crawlers) to access the Service without prior written permission</li>
            <li>Attempt to overwhelm or disrupt the Service through excessive requests or other means</li>
            <li>Reproduce, duplicate, copy, sell, or resell any part of the Service without express written permission</li>
            <li>Generate spam, phishing content, or unsolicited commercial communications</li>
            <li>Use the Service in any manner that could damage, disable, or impair it</li>
          </ul>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>5. No Unlawful or Abusive Use</h2>
        <div className={styles.body}>
          <p>Future Products LLC reserves the right to suspend or permanently block access to users who, in our sole discretion, engage in prohibited conduct, abuse the Service, or attempt to circumvent these Terms. We may take any action we deem appropriate to protect the integrity of the Service and our users, including reporting activity to law enforcement where required.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>6. AI-Generated Content Disclaimer</h2>
        <div className={styles.body}>
          <p>The responses provided by AskAway are generated by artificial intelligence and are provided for informational and general purposes only. They do not constitute professional legal, medical, financial, psychological, or other expert advice.</p>
          <p>AI-generated content may be inaccurate, incomplete, or outdated. You are solely responsible for how you use or act on any information provided by the Service. Always consult a qualified professional before making decisions based on AI-generated responses.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>7. Intellectual Property</h2>
        <div className={styles.body}>
          <p>The AskAway name, logo, and website design are the property of Future Products LLC. You retain ownership of any content you submit. By submitting content, you grant Future Products LLC a limited, non-exclusive license to process that content solely for the purpose of providing the Service.</p>
          <p>AI-generated responses are provided to you for your personal use. We make no representations or warranties about the ownership or copyright status of AI-generated content.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>8. Disclaimer of Warranties</h2>
        <div className={`${styles.body} ${styles.uppercase}`}>
          <p>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>9. Limitation of Liability</h2>
        <div className={`${styles.body} ${styles.uppercase}`}>
          <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, FUTURE PRODUCTS LLC AND ITS MEMBERS, OFFICERS, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, DATA, GOODWILL, OR OTHER INTANGIBLE LOSSES, ARISING OUT OF OR RELATED TO YOUR USE OF OR INABILITY TO USE THE SERVICE.</p>
          <p>IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID US IN THE PAST SIX MONTHS (IF ANY) OR (B) ONE HUNDRED DOLLARS (US $100.00).</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>10. Indemnification</h2>
        <div className={styles.body}>
          <p>You agree to indemnify, defend, and hold harmless Future Products LLC and its members, officers, and agents from and against any claims, liabilities, damages, losses, and expenses (including reasonable legal fees) arising out of or related to: (a) your use of the Service; (b) your violation of these Terms; (c) your violation of any law or the rights of any third party; or (d) any content you submit through the Service.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>11. Third-Party Services</h2>
        <div className={styles.body}>
          <p>AskAway uses third-party services, including Anthropic's AI API and web hosting providers, to operate the Service. We are not responsible for the practices, terms, or content of third-party services. Links to third-party websites, if any, are provided for convenience and do not imply endorsement.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>12. Modifications to the Service and Terms</h2>
        <div className={styles.body}>
          <p>We reserve the right to modify, suspend, or discontinue the Service at any time without notice. We may also update these Terms at any time. The "Last Updated" date at the top of this document will reflect any changes. Your continued use of the Service after changes are posted constitutes your acceptance of the revised Terms. If you do not agree with the revised Terms, you must stop using the Service.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>13. Governing Law</h2>
        <div className={styles.body}>
          <p>These Terms shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of law provisions. Any dispute arising under or related to these Terms shall be resolved in the state or federal courts located in San Francisco County, California, and you consent to the personal jurisdiction of such courts.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>14. Severability</h2>
        <div className={styles.body}>
          <p>If any provision of these Terms is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that the remaining Terms will remain in full force and effect.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>15. Entire Agreement</h2>
        <div className={styles.body}>
          <p>These Terms, together with our <Link href="/privacy">Privacy Policy</Link>, constitute the entire agreement between you and Future Products LLC regarding the Service and supersede any prior agreements or understandings.</p>
        </div>
      </div>

      <div className={styles.section}>
        <h2 className={styles.sectionTitle}>16. Contact</h2>
        <div className={styles.body}>
          <p>For questions about these Terms of Service, please contact us at: askaway.guide</p>
        </div>
      </div>
    </div>
  );
}
